version: "3"
services:
  node:
    container_name: node
    image: ghcr.io/gochain/gochain:${GOCHAIN_TAG:-latest}
    ports:
      - "30303:30303"
      - "30303:30303/udp"
    volumes:
      - .:/gochain
    command: gochain --config /gochain/config.toml --datadir /gochain/node --cache ${GOCHAIN_CACHE:-16000} --rpc --mine --unlock ${GOCHAIN_ACCT} --password /gochain/password.txt --netstats "${NETSTATS_NAME}":${NETSTATS_SECRET}@stats.gochain.io --miner.extradata "${GOCHAIN_EXTRADATA}"
    restart: always
    logging:
      driver: "json-file"
      options:
        max-file: 3
        max-size: 512m
