services:
  node:
    container_name: node
    image: ghcr.io/gochain/gochain:${GOCHAIN_TAG:-testnet}
    ports:
      - "30303:30303"
      - "30303:30303/udp"
    volumes:
      - .:/gochain
    command: gochain --testnet --datadir /gochain/node --cache ${GOCHAIN_CACHE:16000} --rpc
    restart: always
